### ISSUE TITLE
automated curation lab fails (containers, 2.8)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-jupyter-notebooks#32]
When the 'automated curation' lab notebook is run in the kubernetes environment, it fails at the following cell:
```
oakDeneLandingAreaFullPath = "/" + landingAreaDirectoryName + "/oak-dene/clinical-trials/drop-foot"

os.listdir (oakDeneLandingAreaFullPath)
```
with
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-48-6a9a15d261f8> in <module>
      1 oakDeneLandingAreaFullPath = "/" + landingAreaDirectoryName + "/oak-dene/clinical-trials/drop-foot"
      2 
----> 3 os.listdir (oakDeneLandingAreaFullPath)

FileNotFoundError: [Errno 2] No such file or directory: '/deployments/data/landing-area/hospitals/oak-dene/clinical-trials/drop-foot'
```

This is failing as `os.listdir` is being used, which will list files locally - ie on the notebook server, and not on the actual egeria server.

The issue is minor - everything else has worked correctly, and so for 2.8 I propose adding to release notes, and considering how we want to do this properly in the next release

**Comment by planetf1** [comment]
In ad13e865f857eec36ca5466d1d4b079fc8aa63e3 I noticed the lab was updated and the in-dev label removed.

On testing, I get a failure at step 11:
```
​
waitForRunningGovernanceEngine(governDL01Name, governDL01PlatformName, governDL01PlatformURL, petersUserId, assetGovernanceEngineName)
​
printGovernanceEngineStatuses(governDL01Name, governDL01PlatformName, governDL01PlatformURL, petersUserId)
​
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [11], line 1
----> 1 waitForRunningGovernanceEngine(governDL01Name, governDL01PlatformName, governDL01PlatformURL, petersUserId, assetGovernanceEngineName)
      3 printGovernanceEngineStatuses(governDL01Name, governDL01PlatformName, governDL01PlatformURL, petersUserId)

NameError: name 'assetGovernanceEngineName' is not defined
```

This value is referred to but never set

**Comment by mandy-chessell** [comment]
You are right - I am still working on it - hopefully get it finished this week ...

**Comment by planetf1** [comment]
I tried the updated lab (governance-server-operation) which failed at step.22

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [22], in <cell line: 21>()
     17     waitForRunningGovernanceAction(simpleMetadataCatalog, devPlatformName, devPlatformURL, erinsUserId, governanceActionGUID)
     18     printGovernanceAction(simpleMetadataCatalog, devPlatformName, devPlatformURL, erinsUserId, governanceActionGUID)
---> 21 addFileToLandingArea(filesSourceFolder, landingAreaDirectory, "1", "FTP Oak Dene Week 1")

Input In [22], in addFileToLandingArea(sourceFolder, destinationFolder, weekNumber, qualifiedName)
      7 governanceActionGUID = None
      8 governanceActionGUID = initiateGovernanceAction(simpleMetadataCatalog,
      9                                                 devPlatformName,
     10                                                 devPlatformURL,
   (...)
     15                                                 requestParameters,
     16                                                 "Governance Services Lab")
---> 17 waitForRunningGovernanceAction(simpleMetadataCatalog, devPlatformName, devPlatformURL, erinsUserId, governanceActionGUID)
     18 printGovernanceAction(simpleMetadataCatalog, devPlatformName, devPlatformURL, erinsUserId, governanceActionGUID)

File /var/folders/y0/dtxnsmfs0sz8_01kd0hhfjrc0000gn/T/ipykernel_81021/1004445229.py:131, in waitForRunningGovernanceAction(serverName, serverPlatformName, serverPlatformURL, userId, governanceActionGUID)
    129 while not checkGovernanceActionCompletion(governanceActionElement):
    130     governanceActionStatus = governanceActionElement.get('actionStatus')
--> 131     print(" ... Waiting for completion status, current status is: " + governanceActionStatus)
    132     time.sleep(1)
    133     governanceActionElement = getGovernanceAction(serverName, serverPlatformName, serverPlatformURL, userId, governanceActionGUID)

TypeError: can only concatenate str (not "NoneType") to str
```

Is this lab still in development? If so may be worth adding a statement to clarify for the user. Or if not needs a fix.

**Comment by mandy-chessell** [comment]
This is a different lab to the automated curation lab - should be a different issue.  I am happy to fix - it should be working.

**Comment by mandy-chessell** [comment]
I had a think about it and I expect this test was run against the release 3.14 and not against main?  If this is the case then it will fail.  It uses many of the same functions as the automated curation lab that only work in 3.15-SNAPSHOT and later.

It is difficult to tell what the environment is from these comments.

I suggest the governance-server-operation lab has the same comment added to the top to say it is V3.15 or later.

**Comment by planetf1** [comment]
Yes, I tested on 3.14 (as part of release) - I should have clarified.
I will add that disclaimer

**Comment by planetf1** [comment]
Confirmed - tested on 3.15-SNAPSHOT via k8s, fails as expected

<img width="1223" alt="Screenshot 2022-12-15 at 10 05 15" src="https://user-images.githubusercontent.com/7292002/207831469-7ee6eb43-bd66-4bbd-a2dd-5a5d3ccb00c3.png">

This is because the file is written on one platform ,and we try to read on another

For this scenario we would probably expect coco to have a shared file server, and so that is probably what we need
in the chart environment

**Comment by planetf1** [comment]
Opened up odpi/egeria-charts#226 to add support for a shared filesystem for coco

**Comment by mandy-chessell** [comment]
In this notebook all access to the files is done by the same platform.  The failure is in an call made by the jupyter notebook.  The juypyter notebook needs to have access to the same file system as the platform(s).

**Comment by planetf1** [comment]
@mandy-chessell sure. I was thinking generally about access from multiple containers :-) - the references issue should fallow the potential for sharing between any of the containers - clients (we don't have yet), egeria platform, jupyter
