### ISSUE TITLE
Additional files in notebooks - should be removed?

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-jupyter-notebooks#33]
I noticed in ad13e865f857eec36ca5466d1d4b079fc8aa63e3 that a large number of files were added (details below)

I think these may have been included in error
 * checkpoint files represent work in-progress. They do get created when editing, but once the final files are saved, they should go
 * .json files which represent output from running CTS

➜  egeria-jupyter-notebooks git:(main) find . -name '*checkpoint*'
./conformance-testing-labs/.ipynb_checkpoints
./conformance-testing-labs/.ipynb_checkpoints/run-conformance-test-suite-checkpoint.ipynb
./information-architecture/.ipynb_checkpoints
./information-architecture/.ipynb_checkpoints/working-with-standard-models-checkpoint.ipynb
➜  egeria-jupyter-notebooks git:(main)

➜  egeria-jupyter-notebooks git:(main) find . -name '*json*' | head -5
./conformance-testing-labs/profile-details/Entity_proxies.json
./conformance-testing-labs/profile-details/Dynamic_types.json
./conformance-testing-labs/profile-details/Reference_copies.json
./conformance-testing-labs/profile-details/Rehome_instance.json
./conformance-testing-labs/profile-details/Graph_queries.json
➜  egeria-jupyter-notebooks git:(main) find conformance-testing-labs/test-case-details -print | wc -l
     741
➜  egeria-jupyter-notebooks git:(main) find conformance-testing-labs/profile-details -print | wc -l
      17
      
     ➜  egeria-jupyter-notebooks git:(main) find . -name '*json*' | grep -v profile-details | grep -v test-case-details
./conformance-testing-labs/openmetadata_cts_summary.json

**Comment by mandy-chessell** [comment]
They were removed by a subsequent commit.  The .gitignore was not populated for the CTS.  I updated the .gitignore and removed all of the incorrect files.   This went in to the repo in the same PR I thought.

**Comment by mandy-chessell** [comment]
Umm - trange - when I look here the files are not present - https://github.com/odpi/egeria-jupyter-notebooks/tree/main/conformance-testing-labs

You can also see the commit "implement .gitignore" throughout the git repo ...

Have you run the CTS in this branch?

**Comment by planetf1** [comment]
Fresh clone, MOST are gone, but we still have:

./information-architecture/.ipynb_checkpoints
./information-architecture/.ipynb_checkpoints/working-with-standard-models-checkpoint.ipynb

Minor, but good to cleanup

**Comment by planetf1** [comment]
On the json files, I suspect you were correct - that I would have run the CTS earlier, creating those files, and/or indeed other notebook edits.. Combined with looking at the PR commits and seeing the changes I concluded (wrongly) the files were introduced - they weren't. thanks for sorting the .gitignore sorted to avoid this in future

**Comment by mandy-chessell** [comment]
I can fix them the next time I push the labs

**Comment by planetf1** [comment]
All looks clean now - closing
