### ISSUE TITLE
Jupyter notebooks to another repository?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-jupyter-notebooks#4]
At the moment our Jupyter notebooks for the various labs are all embedded in this core repository -- as with other examples (Helm charts, samples, etc) this means that we take a very long hit before we can merge anything while we wait for Java code to build (which the notebooks don't touch at all)...

I vaguely recall we'd previously discussing moving these out to e.g. the `egeria-samples` repository (or perhaps some other repository), but that we were waiting until some of the other dependent material was moved (like the Helm charts) (?)

Now that the Helm charts are in their own dedicated repository and no longer embedded here, would now be a logical time to move these lab notebooks out as well -- or was there something else we were dependent on / waiting on (?)

**Comment by planetf1** [comment]
this move is mostly done -- the development versions of the charts now use this repository as the source of the notebooks.

**Comment by planetf1** [comment]
this move is complete
