### ISSUE TITLE
Testing the Jupyter Notebooks on k8s with V4

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-jupyter-notebooks#57]
I've created a test summary spreadsheet to track testing of V4 against the Jupyter notebooks. I'm planning on making some enhancements to indicate sequence of tests since the order seems to be quite important - not just in terms of name clashes but sometimes in terms of resource consumption. There are different tabs for testing different repository types on different days.

Note that this testing suggests some future notebook cleanup and is useful in experimenting with resource allocation,monitoring, and management with k8s environments. Testing is not showing issues in Egeria itself.

[Lab Tests.numbers.zip](https://github.com/odpi/egeria-charts/files/11057786/Lab.Tests.numbers.zip)

I'll continue testing..

**Comment by dwolfson** [comment]
A bit of an update.  After some bug fixes and updates to the notebooks, the labs seem to be running cleanly. Longer term, there is refactoring and cleanup to do but they are currently stable.

**Comment by planetf1** [comment]
Most appeared to be timing -- but the first was a logic issue when running labs in different orders. Was this addressed? I don't see a specific issue/PR ?
